// Code generated by the FlatBuffers compiler. DO NOT EDIT.

//nolint
package bouncer_flatbuf

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AnyProto struct {
	_tab flatbuffers.Table
}

func GetRootAsAnyProto(buf []byte, offset flatbuffers.UOffsetT) *AnyProto {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AnyProto{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AnyProto) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AnyProto) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AnyProto) Buf(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AnyProto) BufLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AnyProto) BufBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AnyProto) MutateBuf(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func AnyProtoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AnyProtoAddBuf(builder *flatbuffers.Builder, buf flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(buf), 0)
}
func AnyProtoStartBufVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AnyProtoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
