// Code generated by the FlatBuffers compiler. DO NOT EDIT.

//nolint
package bouncer_flatbuf

import "strconv"

type Payload byte

const (
	PayloadNONE     Payload = 0
	PayloadAnyProto Payload = 1
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:     "NONE",
	PayloadAnyProto: "AnyProto",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":     PayloadNONE,
	"AnyProto": PayloadAnyProto,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
