// Code generated by the FlatBuffers compiler. DO NOT EDIT.

//nolint
package bouncer_flatbuf

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PopRecordRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPopRecordRequest(buf []byte, offset flatbuffers.UOffsetT) *PopRecordRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PopRecordRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PopRecordRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PopRecordRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PopRecordRequest) AckUuid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PopRecordRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PopRecordRequestAddAckUuid(builder *flatbuffers.Builder, ackUuid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ackUuid), 0)
}
func PopRecordRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
