// Code generated by the FlatBuffers compiler. DO NOT EDIT.

//nolint
package bouncer_flatbuf

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PopRecordReply struct {
	_tab flatbuffers.Table
}

func GetRootAsPopRecordReply(buf []byte, offset flatbuffers.UOffsetT) *PopRecordReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PopRecordReply{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PopRecordReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PopRecordReply) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PopRecordReply) Uuid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PopRecordReply) Record(obj *Record) *Record {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Record)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PopRecordReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PopRecordReplyAddUuid(builder *flatbuffers.Builder, uuid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uuid), 0)
}
func PopRecordReplyAddRecord(builder *flatbuffers.Builder, record flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(record), 0)
}
func PopRecordReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
