clients:
  - priority: "low"
    workload:
    - rps: 1000
      duration: 5s
    - rps: 5000
      duration: 15s
    rq_timeout: 5s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 8080
  - priority: "high"
    workload:
    - rps: 1000
      duration: 15s
    - rps: 5000
      duration: 5s
    rq_timeout: 5s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 8080
  - priority: "default"
    workload:
    - rps: 1000
      duration: 10s
    - rps: 5000
      duration: 10s
    rq_timeout: 5s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 8080
servers:
  - profile:
    - duration: 20s
      pops_per_sec: 3500
    listen_port: 8080
    threads: 8