clients:
  - workload:
    - rps: 1000
      duration: 5s
    - rps: 1500
      duration: 5s
    - rps: 2000
      duration: 5s
    - rps: 2500
      duration: 5s
    - rps: 3000
      duration: 10s
    - rps: 500
      duration: 30s
    rq_timeout: 500s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 10000
servers:
  - profile:
    - duration: 60s
      latency_distribution:
      - weight: 50
        latency: 3ms
      - weight: 5
        latency: 5ms
      - weight: 5
        latency: 7ms
      - weight: 5
        latency: 10ms
      - weight: 5
        latency: 15ms
      - weight: 5
        latency: 22ms
      - weight: 5
        latency: 34ms
      - weight: 5
        latency: 51ms
      - weight: 5
        latency: 76ms
      - weight: 5
        latency: 115ms
      - weight: 5
        latency: 150ms
    listen_port: 9002
    threads: 8
