clients:
  - workload:
    - rps: 1000
      duration: 10s
    - rps: 5000
      duration: 10s
    - rps: 1000
      duration: 40s
    rq_timeout: 5s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 8080
    priority: "low"
  - workload:
    - rps: 1000
      duration: 20s
    - rps: 2000
      duration: 2s
    - rps: 3000
      duration: 2s
    - rps: 4000
      duration: 2s
    - rps: 5000
      duration: 2s
    - rps: 6000
      duration: 32s
    rq_timeout: 5s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 8080
    priority: "default"
  - workload:
    - rps: 1000
      duration: 30s
    - rps: 1500
      duration: 5s
    - rps: 2000
      duration: 5s
    - rps: 2500
      duration: 5s
    - rps: 3500
      duration: 5s
    - rps: 4000
      duration: 5s
    - rps: 4500
      duration: 5s
    rq_timeout: 5s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 8080
    priority: "high"
servers:
  - profile:
    - duration: 62s
      pops_per_sec: 4000
    listen_port: 8080
    threads: 8
